version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/.github/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'build'
      include: 'scope'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    groups:
      dependencies:
        patterns:
          - 'rlespinasse/slugify-value'
          - 'rlespinasse/shortify-git-revision'
        update-types:
          - 'minor'
          - 'patch'
