version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "rlespinasse"
    labels: [ ]
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "feat: "
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "rlespinasse/slugify-value"
          - "rlespinasse/shortify-git-revision"
    reviewers:
      - "rlespinasse"
    labels: [ ]
