name: Build

on:
  push:
    branches:
      - v3.x
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run all
      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.3.4
          branches: |
            [
              'v2.x',
              'v3.x'
            ]
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}

  os-test:
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Output
        run: |
          echo "Partial variables"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART }}"
          echo "Slug variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG }}"
          echo "Slug URL variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_URL }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_URL }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
          echo "Short SHA variables"
          echo "   sha                 : ${{ env.GITHUB_SHA_SHORT }}"
          echo "   pull request sha    : ${{ env.GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT }}"
      - name: Case Sensitive Output
        run: |
          echo "Slug variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_CS }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_CS }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_CS }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_CS }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_CS }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_CS }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_CS }}"
          echo "Slug URL variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_URL_CS }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_URL_CS }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL_CS }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_URL_CS }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_URL_CS }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_URL_CS }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_URL_CS }}"

  win-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Output
        run: |
          echo "Partial variables"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART"
          echo "Slug variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG"
          echo "   ref                 : $env:GITHUB_REF_SLUG"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG"
          echo "Slug URL variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG_URL"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG_URL"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG_URL"
          echo "   ref                 : $env:GITHUB_REF_SLUG_URL"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG_URL"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG_URL"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG_URL"
          echo "Short SHA variables"
          echo "   sha                 : $env:GITHUB_SHA_SHORT"
          echo "   pull request sha    : $env:GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT"
      - name: Case Sensitive Output
        run: |
          echo "Slug variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG_CS"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG_CS"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG_CS"
          echo "   ref                 : $env:GITHUB_REF_SLUG_CS"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG_CS"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG_CS"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG_CS"
          echo "Slug URL variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG_URL_CS"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG_URL_CS"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG_URL_CS"
          echo "   ref                 : $env:GITHUB_REF_SLUG_URL_CS"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG_URL_CS"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG_URL_CS"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG_URL_CS"
