name: Build OS-Dependent

on:
  push:
    branches:
      - v3.x
  pull_request:
    branches:
      - v3.x

jobs:
  use-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - uses: ./
      - name: Output
        run: |
          echo "Partial variables"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART }}"
          echo "Slug variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG }}"
          echo "Slug URL variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_URL }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_URL }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
          echo "Short SHA variables"
          echo "   sha                 : ${{ env.GITHUB_SHA_SHORT }}"
          echo "   pull request sha    : ${{ env.GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT }}"
      - name: Case Sensitive Output
        run: |
          echo "Slug variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_CS }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_CS }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_CS }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_CS }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_CS }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_CS }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_CS }}"
          echo "Slug URL variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_URL_CS }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_URL_CS }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL_CS }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_URL_CS }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_URL_CS }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_URL_CS }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_URL_CS }}"

  use-on-macos:
    runs-on: macos-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - uses: ./
      - name: Output
        run: |
          echo "Partial variables"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART }}"
          echo "Slug variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG }}"
          echo "Slug URL variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_URL }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_URL }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
          echo "Short SHA variables"
          echo "   sha                 : ${{ env.GITHUB_SHA_SHORT }}"
          echo "   pull request sha    : ${{ env.GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT }}"
      - name: Case Sensitive Output
        run: |
          echo "Slug variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_CS }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_CS }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_CS }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_CS }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_CS }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_CS }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_CS }}"
          echo "Slug URL variables"
          echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_URL_CS }}"
          echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_URL_CS }}"
          echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL_CS }}"
          echo "   ref                 : ${{ env.GITHUB_REF_SLUG_URL_CS }}"
          echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_URL_CS }}"
          echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_URL_CS }}"
          echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_URL_CS }}"

  use-on-windows:
    runs-on: windows-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - uses: ./
      - name: Output
        run: |
          echo "Partial variables"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART"
          echo "Slug variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG"
          echo "   ref                 : $env:GITHUB_REF_SLUG"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG"
          echo "Slug URL variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG_URL"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG_URL"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG_URL"
          echo "   ref                 : $env:GITHUB_REF_SLUG_URL"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG_URL"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG_URL"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG_URL"
          echo "Short SHA variables"
          echo "   sha                 : $env:GITHUB_SHA_SHORT"
          echo "   pull request sha    : $env:GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT"
      - name: Case Sensitive Output
        run: |
          echo "Slug variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG_CS"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG_CS"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG_CS"
          echo "   ref                 : $env:GITHUB_REF_SLUG_CS"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG_CS"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG_CS"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG_CS"
          echo "Slug URL variables"
          echo "   repository          : $env:GITHUB_REPOSITORY_SLUG_URL_CS"
          echo "   repository owner    : $env:GITHUB_REPOSITORY_OWNER_PART_SLUG_URL_CS"
          echo "   repository name     : $env:GITHUB_REPOSITORY_NAME_PART_SLUG_URL_CS"
          echo "   ref                 : $env:GITHUB_REF_SLUG_URL_CS"
          echo "   head ref            : $env:GITHUB_HEAD_REF_SLUG_URL_CS"
          echo "   base ref            : $env:GITHUB_BASE_REF_SLUG_URL_CS"
          echo "   event ref           : $env:GITHUB_EVENT_REF_SLUG_URL_CS"
