name: '[v3] Release DryRun'

on:
  push:
    branches-ignore:
      - v*.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
        shell: bash
      - run: npm run all
        shell: bash
      - uses: ./
      - uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [
              "${{ env.GITHUB_REF_NAME }}"
            ]
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
