name: Release DryRun

on:
  push:
    branches-ignore:
      - v*.x

jobs:
  release-dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - uses: ./
      - uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              "${{ env.GITHUB_REF_SLUG }}"
            ]
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
